FROM golang:1.6

ADD . /go/src/github.com/vidu171/dell-ecs-s3-client

RUN apt-get update && apt-get install -y --no-install-recommends \
		vim \
	&& rm -rf /var/list/apt/lists/*

WORKDIR /go/src/github.com/vidu171/dell-ecs-s3-client
CMD ["make", "get-deps", "unit-old-go-race-cover"]
