// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package awsendpointdiscoverytest

import (
	"github.com/vidu171/dell-ecs-s3-client/private/protocol"
)

var exceptionFromCode = map[string]func(protocol.ResponseMetadata) error{}
